# Generated by Django 3.2.6 on 2021-09-03 00:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_post_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 0, 16, 11, 961462, tzinfo=utc)),
        ),
    ]
